graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

0["crm:E12_Production"]:::Temporal_Entity -->|crm:P01i_is_domain_of| 1["crm:PC14_carried_out_by"]:::PC_Classes
7["crm:PC14_carried_out_by"]:::PC_Classes -->|crm:P14.1_in_the_role_of| 8["crm:E55_Type"]:::Type
9["crm:E78_Collection"]:::Physical_Thing -->|crm:P147i_was_curated_by| 2["crm:E87_Curation_Activity"]:::Temporal_Entity
9["crm:E78_Collection"]:::Physical_Thing -->|crm:P108i_was_produced_by| 0["crm:E12_Production"]:::Temporal_Entity
13["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 5["crm:E39_Actor"]:::Actor
9["crm:E78_Collection"]:::Physical_Thing -->|crm:P52_has_current_owner| 10["crm:E39_Actor"]:::Actor
13["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P16_used_specific_object| 15["crm:E33_Linguistic_Object"]:::Conceptual_Object
16["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 17[xsd:dateTime]:::Literal
7["crm:PC14_carried_out_by"]:::PC_Classes -->|crm:P02_has_range| 18["crm:E39_Actor"]:::Actor
0["crm:E12_Production"]:::Temporal_Entity -->|crm:P01i_is_domain_of| 7["crm:PC14_carried_out_by"]:::PC_Classes
16["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 21[xsd:dateTime]:::Literal
9["crm:E78_Collection"]:::Physical_Thing -->|crm:P50_current_keeper| 22["crm:E39_Actor"]:::Actor
13["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P4_has_time-span| 16["crm:E52_Time-Span"]:::Time-Span
2["crm:E87_Curation_Activity"]:::Temporal_Entity -->|crm:P14_carried_out_by| 19["crm:E39_Actor"]:::Actor
1["crm:PC14_carried_out_by"]:::PC_Classes -->|crm:P141i_was_assigned_by| 13["crm:E13_Attribute_Assignment"]:::Temporal_Entity
